controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    # use_sim_time: true

    mecanumbot_drive_controller:
      type: mecanumbot_controller/MecanumbotDriveController

    joint_state_controller:
      type: joint_state_broadcaster/JointStateBroadcaster



mecanumbot_drive_controller:
  ros__parameters:
    fl_wheel_joint_name: fl_wheel_joint
    fr_wheel_joint_name: fr_wheel_joint
    rl_wheel_joint_name: rl_wheel_joint
    rr_wheel_joint_name: rr_wheel_joint
    wheel_radius: 0.0485
    wheel_distance:
      width: 0.383
      length: 0.37 